/*
 * SOLIDserver API
 *
 * OpenAPI 3.0.2 API definition for SOLIDserver service from EfficientIP.<p>Copyright © 2000-2021 EfficientIP</p><p><em>All specifications and information regarding the products in  this document are subject to change without notice and should not be  construed as a commitment by EfficientIP. EfficientIP assumes no  responsibility or liability for any mistakes or inaccuracies that may appear  in this document. All statements and recommendations in this document are  believed to be accurate but are presented without warranty. Users must take  full responsibility for their application of any product.</em></p><p>Generated (Monday 14th of June 2021 12:30:34 PM)</p>
 *
 * API version: 2.0
 * Contact: support-api@efficientip.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdsclient

import (
	"encoding/json"
)

// DhcpGroupDeleteSuccessData struct for DhcpGroupDeleteSuccessData
type DhcpGroupDeleteSuccessData struct {
	// The database identifier (ID) of the object you deleted.
	GroupId *string `json:"group_id,omitempty"`
}

// NewDhcpGroupDeleteSuccessData instantiates a new DhcpGroupDeleteSuccessData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDhcpGroupDeleteSuccessData() *DhcpGroupDeleteSuccessData {
	this := DhcpGroupDeleteSuccessData{}
	return &this
}

// NewDhcpGroupDeleteSuccessDataWithDefaults instantiates a new DhcpGroupDeleteSuccessData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDhcpGroupDeleteSuccessDataWithDefaults() *DhcpGroupDeleteSuccessData {
	this := DhcpGroupDeleteSuccessData{}
	return &this
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *DhcpGroupDeleteSuccessData) GetGroupId() string {
	if o == nil || o.GroupId == nil {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpGroupDeleteSuccessData) GetGroupIdOk() (*string, bool) {
	if o == nil || o.GroupId == nil {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *DhcpGroupDeleteSuccessData) HasGroupId() bool {
	if o != nil && o.GroupId != nil {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *DhcpGroupDeleteSuccessData) SetGroupId(v string) {
	o.GroupId = &v
}

func (o DhcpGroupDeleteSuccessData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.GroupId != nil {
		toSerialize["group_id"] = o.GroupId
	}
	return json.Marshal(toSerialize)
}

type NullableDhcpGroupDeleteSuccessData struct {
	value *DhcpGroupDeleteSuccessData
	isSet bool
}

func (v NullableDhcpGroupDeleteSuccessData) Get() *DhcpGroupDeleteSuccessData {
	return v.value
}

func (v *NullableDhcpGroupDeleteSuccessData) Set(val *DhcpGroupDeleteSuccessData) {
	v.value = val
	v.isSet = true
}

func (v NullableDhcpGroupDeleteSuccessData) IsSet() bool {
	return v.isSet
}

func (v *NullableDhcpGroupDeleteSuccessData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDhcpGroupDeleteSuccessData(val *DhcpGroupDeleteSuccessData) *NullableDhcpGroupDeleteSuccessData {
	return &NullableDhcpGroupDeleteSuccessData{value: val, isSet: true}
}

func (v NullableDhcpGroupDeleteSuccessData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDhcpGroupDeleteSuccessData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


