/*
 * SOLIDserver API
 *
 * OpenAPI 3.0.2 API definition for SOLIDserver service from EfficientIP.<p>Copyright © 2000-2021 EfficientIP</p><p><em>All specifications and information regarding the products in  this document are subject to change without notice and should not be  construed as a commitment by EfficientIP. EfficientIP assumes no  responsibility or liability for any mistakes or inaccuracies that may appear  in this document. All statements and recommendations in this document are  believed to be accurate but are presented without warranty. Users must take  full responsibility for their application of any product.</em></p><p>Generated (Monday 14th of June 2021 12:30:34 PM)</p>
 *
 * API version: 2.0
 * Contact: support-api@efficientip.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdsclient

import (
	"encoding/json"
)

// DhcpServer6DataData struct for DhcpServer6DataData
type DhcpServer6DataData struct {
	// The name of the class applied to the DHCPv6 server, it can be preceded by the class directory.
	Server6ClassName *string `json:"server6_class_name,omitempty"`
	// The class parameters applied to the DHCPv6 server and their value: <b>&lt;class-parameter1&gt;=&lt;value1&gt;&amp;&lt;class-parameter2&gt;=&lt;value2&gt;&amp;</b>... .
	Server6ClassParameters *[]ApiClassParameterOutputEntry `json:"server6_class_parameters,omitempty"`
	// The description of the DHCPv6 server.
	Server6Comment *string `json:"server6_comment,omitempty"`
	// The database identifier (ID) of the DHCPv6 server, a unique numeric key value automatically incremented when you add a DHCPv6 server.
	Server6Id *string `json:"server6_id,omitempty"`
	// Internal use. Not documented.
	Server6LastRefreshTime *string `json:"server6_last_refresh_time,omitempty"`
	// The name of the DHCPv6 server.
	Server6Name *string `json:"server6_name,omitempty"`
	// The status of the DHCPv6 server: <table><caption>dhcp6_state possible values</caption><br/><thead><tr><th>Status</th><th>Description</th></tr><br/></thead><br/><tbody><tr><td >ER</td><td >The license used in SOLIDserver is not compliant with the added server: the license is invalid.</td></tr><tr><td >ES</td><td >The server configuration could not be parsed properly.</td></tr><tr><td >ET</td><td >The server does not answer anymore due to a scheduled configuration of the server.</td></tr><tr><td >IS</td><td >There was a setting error during the server declaration. For instance, some settings were added to a server that does not support them or a smart architecture is not managing any physical server.</td></tr><tr><td >IC</td><td >The SSL credentials are invalid</td></tr><tr><td >IP</td><td >The account used to add the Agentless DHCP server does not have sufficient privileges to manage it.</td></tr><tr><td >LS</td><td >The server configuration is not viable.</td></tr><tr><td >N</td><td >The server does not have a status as it has not synchronized yet.</td></tr><tr><td >Y</td><td >The server is operational.</td></tr></tbody></table></p><br/>
	Server6State *string `json:"server6_state,omitempty"`
	// The synchronization status of the DHCPv6 server. <b>1</b> indicates that the server is currently being synchronized.
	Server6Synching *string `json:"server6_synching,omitempty"`
	// The type of the DHCPv6 server: <table><caption>dhcp6_type possible values</caption><br/><thead><tr><th>Type</th><th>Description</th></tr><br/></thead><br/><tbody><tr><td >ipm</td><td >EfficientIP DHCP server or EfficientIP DHCP Package</td></tr><tr><td >vdhcp</td><td >EfficientIP DHCP smart architecture</td></tr></tbody></table></p><br/>
	Server6Type *string `json:"server6_type,omitempty"`
	// Internal use. Not documented.
	Server6Uboottime *string `json:"server6_uboottime,omitempty"`
	// The version details of the DHCPv6 server.
	Server6Version *string `json:"server6_version,omitempty"`
	// The IP address of the DHCP server, in hexadecimal format.
	Server6Addr *string `json:"server6_addr,omitempty"`
	// Internal use. Not documented.
	Server6HttpsLogin *string `json:"server6_https_login,omitempty"`
	// The DHCPv6 server package information. <b>Y</b> for an EfficientIP DHCP Package server, <b>N</b> for an appliance or virtual machine, <b>U</b> the package information is irrelevant. For servers with a <b>dhcp6_type</b> set to <b>ipm</b>, <b>U</b> indicates either EfficientIP DHCP Packages or appliances/virtual machines.
	Server6IsPackage *string `json:"server6_is_package,omitempty"`
	// A way to determine if the server can update any other module <b>(1)</b>.
	Server6Isolated *string `json:"server6_isolated,omitempty"`
	// The Multi-status information is displayed as follows: <i>&lt;number-of-instances&gt;@&lt;message-number&gt;@&lt;multi-status-severity&gt;@&lt;module&gt;</i>. The different severity levels are:<br><b>Multi-status severity levels</b>    <table border=1>        <thead>        <tr >            <td><b>Message number</b></td>            <td><b>Severity</b></td>            <td><b>Description</b></td>        </tr>        </thead>        <tbody>        <tr  valign=middle>            <td>0 - 16</td>            <td>Emergency</td>            <td>The object configuration prevents the system from running properly. Action is required.</td>        </tr>        <tr  valign=middle>            <td>17 - 33</td>            <td>Critical</td>            <td>The object configuration is in critical conditions. Immediate action is recommended.</td>        </tr>        <tr  valign=middle>            <td>34 - 50</td>            <td>Error</td>            <td>The object configuration failed at some level. Action is recommended.</td>        </tr>        <tr  valign=middle>            <td>51 - 66</td>            <td>Warning</td>            <td>The object configuration triggers error messages if no action is taken. Action to be taken at your discretion.</td>        </tr>        <tr  valign=middle>            <td>67 - 83</td>            <td>Notice</td>            <td>The object configuration is normal but undergoing events that might trigger errors. No immediate action required.</td>        </tr>        <tr  valign=middle>            <td>84 - 100</td>            <td>Informational</td>            <td>The object configuration is normal, operational messages (might inform you about potential incompatibilities with other modules, etc). No action required.</td>        </tr>        </tbody></table>
	Server6Multistatus *string `json:"server6_multistatus,omitempty"`
	// TODO:dhcp6_server6_list.output.reverse_proxy_conf
	ReverseProxyConf *string `json:"reverse_proxy_conf,omitempty"`
	// Internal use. Not documented.
	Server6SnmpId *string `json:"server6_snmp_id,omitempty"`
	// Internal use. Not documented.
	Server6SnmpPort *string `json:"server6_snmp_port,omitempty"`
	// Internal use. Not documented.
	Server6SnmpProfileId *string `json:"server6_snmp_profile_id,omitempty"`
	// Internal use. Not documented.
	Server6SnmpRetry *string `json:"server6_snmp_retry,omitempty"`
	// Internal use. Not documented.
	Server6SnmpTimeout *string `json:"server6_snmp_timeout,omitempty"`
	// Internal use. Not documented.
	Server6SnmpUseTcp *string `json:"server6_snmp_use_tcp,omitempty"`
	// Internal use. Not documented.
	Server6StatEnabled *string `json:"server6_stat_enabled,omitempty"`
	// Internal use. Not documented.
	Server6StatNiceness *string `json:"server6_stat_niceness,omitempty"`
	// Internal use. Not documented.
	Server6StatPeriod *string `json:"server6_stat_period,omitempty"`
	// Internal use. Not documented.
	Server6StatTime *string `json:"server6_stat_time,omitempty"`
	// The total number of servers managed by the DHCPv6 smart architecture.
	TotalSmartMembers *string `json:"total_smart_members,omitempty"`
	// The type of the DHCPv6 smart architecture.<table><caption>vdhcp6_arch possible values</caption><br/><thead><tr><th>Type</th><th>Description</th></tr><br/></thead><br/><tbody><tr><td >single</td><td >The Single-Server smart architecture manages a single DHCPv6 server.</td></tr><tr><td >splitscope</td><td >The Split-Scope smart architecture sets a pair of DHCP servers in a configuration where the two scopes listen to the same subnet, but the range of addresses is divided.</td></tr><tr><td >stateless</td><td >The Stateless smart architecture offers a limited number of options to the DHCP clients. The IP address is delivered thanks to the subnet gateway and it is impossible to create any ranges or statics or to retrieve any leases.</td></tr></tbody></table></p><br/>
	SmartArch *string `json:"smart_arch,omitempty"`
	// The list of the servers managed by the DHCPv6 smart architecture, as follows: <b>&lt;dhcp6_name&gt;,&lt;dhcp6_name&gt;,...</b> .
	SmartMembersName *string `json:"smart_members_name,omitempty"`
	// Internal use. Not documented.
	SmartParam1 *string `json:"smart_param1,omitempty"`
	// The type of the DHCPv6 smart architecture managing the DHCPv6 server. No value indicates that the server is not managed by a smart architecture or is a smart architecture itself.
	SmartParentArch *string `json:"smart_parent_arch,omitempty"`
	// The database identifier (ID) of the DHCPv6 smart architecture managing the DHCPv6 server. <b>0</b> indicates that the server is not managed by a smart architecture or is a smart architecture itself.
	SmartParentId *string `json:"smart_parent_id,omitempty"`
	// The name of the DHCPv6 smart architecture managing the DHCPv6 server. <b>#</b> indicates that the server is not managed by a smart architecture or is a smart architecture itself.
	SmartParentName *string `json:"smart_parent_name,omitempty"`
	// The database identifier (ID) of the DHCPv6 smart architecture the server belongs to.
	SmartRef1Server6Id *string `json:"smart_ref1_server6_id,omitempty"`
	// Internal use. Not documented.
	SmartRef1Server6Name *string `json:"smart_ref1_server6_name,omitempty"`
	// Internal use. Not documented.
	SmartRef2Server6Id *string `json:"smart_ref2_server6_id,omitempty"`
	// Internal use. Not documented.
	SmartRef2Server6Name *string `json:"smart_ref2_server6_name,omitempty"`
}

// NewDhcpServer6DataData instantiates a new DhcpServer6DataData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDhcpServer6DataData() *DhcpServer6DataData {
	this := DhcpServer6DataData{}
	return &this
}

// NewDhcpServer6DataDataWithDefaults instantiates a new DhcpServer6DataData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDhcpServer6DataDataWithDefaults() *DhcpServer6DataData {
	this := DhcpServer6DataData{}
	return &this
}

// GetServer6ClassName returns the Server6ClassName field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6ClassName() string {
	if o == nil || o.Server6ClassName == nil {
		var ret string
		return ret
	}
	return *o.Server6ClassName
}

// GetServer6ClassNameOk returns a tuple with the Server6ClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6ClassNameOk() (*string, bool) {
	if o == nil || o.Server6ClassName == nil {
		return nil, false
	}
	return o.Server6ClassName, true
}

// HasServer6ClassName returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6ClassName() bool {
	if o != nil && o.Server6ClassName != nil {
		return true
	}

	return false
}

// SetServer6ClassName gets a reference to the given string and assigns it to the Server6ClassName field.
func (o *DhcpServer6DataData) SetServer6ClassName(v string) {
	o.Server6ClassName = &v
}

// GetServer6ClassParameters returns the Server6ClassParameters field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6ClassParameters() []ApiClassParameterOutputEntry {
	if o == nil || o.Server6ClassParameters == nil {
		var ret []ApiClassParameterOutputEntry
		return ret
	}
	return *o.Server6ClassParameters
}

// GetServer6ClassParametersOk returns a tuple with the Server6ClassParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6ClassParametersOk() (*[]ApiClassParameterOutputEntry, bool) {
	if o == nil || o.Server6ClassParameters == nil {
		return nil, false
	}
	return o.Server6ClassParameters, true
}

// HasServer6ClassParameters returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6ClassParameters() bool {
	if o != nil && o.Server6ClassParameters != nil {
		return true
	}

	return false
}

// SetServer6ClassParameters gets a reference to the given []ApiClassParameterOutputEntry and assigns it to the Server6ClassParameters field.
func (o *DhcpServer6DataData) SetServer6ClassParameters(v []ApiClassParameterOutputEntry) {
	o.Server6ClassParameters = &v
}

// GetServer6Comment returns the Server6Comment field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6Comment() string {
	if o == nil || o.Server6Comment == nil {
		var ret string
		return ret
	}
	return *o.Server6Comment
}

// GetServer6CommentOk returns a tuple with the Server6Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6CommentOk() (*string, bool) {
	if o == nil || o.Server6Comment == nil {
		return nil, false
	}
	return o.Server6Comment, true
}

// HasServer6Comment returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6Comment() bool {
	if o != nil && o.Server6Comment != nil {
		return true
	}

	return false
}

// SetServer6Comment gets a reference to the given string and assigns it to the Server6Comment field.
func (o *DhcpServer6DataData) SetServer6Comment(v string) {
	o.Server6Comment = &v
}

// GetServer6Id returns the Server6Id field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6Id() string {
	if o == nil || o.Server6Id == nil {
		var ret string
		return ret
	}
	return *o.Server6Id
}

// GetServer6IdOk returns a tuple with the Server6Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6IdOk() (*string, bool) {
	if o == nil || o.Server6Id == nil {
		return nil, false
	}
	return o.Server6Id, true
}

// HasServer6Id returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6Id() bool {
	if o != nil && o.Server6Id != nil {
		return true
	}

	return false
}

// SetServer6Id gets a reference to the given string and assigns it to the Server6Id field.
func (o *DhcpServer6DataData) SetServer6Id(v string) {
	o.Server6Id = &v
}

// GetServer6LastRefreshTime returns the Server6LastRefreshTime field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6LastRefreshTime() string {
	if o == nil || o.Server6LastRefreshTime == nil {
		var ret string
		return ret
	}
	return *o.Server6LastRefreshTime
}

// GetServer6LastRefreshTimeOk returns a tuple with the Server6LastRefreshTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6LastRefreshTimeOk() (*string, bool) {
	if o == nil || o.Server6LastRefreshTime == nil {
		return nil, false
	}
	return o.Server6LastRefreshTime, true
}

// HasServer6LastRefreshTime returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6LastRefreshTime() bool {
	if o != nil && o.Server6LastRefreshTime != nil {
		return true
	}

	return false
}

// SetServer6LastRefreshTime gets a reference to the given string and assigns it to the Server6LastRefreshTime field.
func (o *DhcpServer6DataData) SetServer6LastRefreshTime(v string) {
	o.Server6LastRefreshTime = &v
}

// GetServer6Name returns the Server6Name field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6Name() string {
	if o == nil || o.Server6Name == nil {
		var ret string
		return ret
	}
	return *o.Server6Name
}

// GetServer6NameOk returns a tuple with the Server6Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6NameOk() (*string, bool) {
	if o == nil || o.Server6Name == nil {
		return nil, false
	}
	return o.Server6Name, true
}

// HasServer6Name returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6Name() bool {
	if o != nil && o.Server6Name != nil {
		return true
	}

	return false
}

// SetServer6Name gets a reference to the given string and assigns it to the Server6Name field.
func (o *DhcpServer6DataData) SetServer6Name(v string) {
	o.Server6Name = &v
}

// GetServer6State returns the Server6State field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6State() string {
	if o == nil || o.Server6State == nil {
		var ret string
		return ret
	}
	return *o.Server6State
}

// GetServer6StateOk returns a tuple with the Server6State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6StateOk() (*string, bool) {
	if o == nil || o.Server6State == nil {
		return nil, false
	}
	return o.Server6State, true
}

// HasServer6State returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6State() bool {
	if o != nil && o.Server6State != nil {
		return true
	}

	return false
}

// SetServer6State gets a reference to the given string and assigns it to the Server6State field.
func (o *DhcpServer6DataData) SetServer6State(v string) {
	o.Server6State = &v
}

// GetServer6Synching returns the Server6Synching field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6Synching() string {
	if o == nil || o.Server6Synching == nil {
		var ret string
		return ret
	}
	return *o.Server6Synching
}

// GetServer6SynchingOk returns a tuple with the Server6Synching field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6SynchingOk() (*string, bool) {
	if o == nil || o.Server6Synching == nil {
		return nil, false
	}
	return o.Server6Synching, true
}

// HasServer6Synching returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6Synching() bool {
	if o != nil && o.Server6Synching != nil {
		return true
	}

	return false
}

// SetServer6Synching gets a reference to the given string and assigns it to the Server6Synching field.
func (o *DhcpServer6DataData) SetServer6Synching(v string) {
	o.Server6Synching = &v
}

// GetServer6Type returns the Server6Type field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6Type() string {
	if o == nil || o.Server6Type == nil {
		var ret string
		return ret
	}
	return *o.Server6Type
}

// GetServer6TypeOk returns a tuple with the Server6Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6TypeOk() (*string, bool) {
	if o == nil || o.Server6Type == nil {
		return nil, false
	}
	return o.Server6Type, true
}

// HasServer6Type returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6Type() bool {
	if o != nil && o.Server6Type != nil {
		return true
	}

	return false
}

// SetServer6Type gets a reference to the given string and assigns it to the Server6Type field.
func (o *DhcpServer6DataData) SetServer6Type(v string) {
	o.Server6Type = &v
}

// GetServer6Uboottime returns the Server6Uboottime field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6Uboottime() string {
	if o == nil || o.Server6Uboottime == nil {
		var ret string
		return ret
	}
	return *o.Server6Uboottime
}

// GetServer6UboottimeOk returns a tuple with the Server6Uboottime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6UboottimeOk() (*string, bool) {
	if o == nil || o.Server6Uboottime == nil {
		return nil, false
	}
	return o.Server6Uboottime, true
}

// HasServer6Uboottime returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6Uboottime() bool {
	if o != nil && o.Server6Uboottime != nil {
		return true
	}

	return false
}

// SetServer6Uboottime gets a reference to the given string and assigns it to the Server6Uboottime field.
func (o *DhcpServer6DataData) SetServer6Uboottime(v string) {
	o.Server6Uboottime = &v
}

// GetServer6Version returns the Server6Version field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6Version() string {
	if o == nil || o.Server6Version == nil {
		var ret string
		return ret
	}
	return *o.Server6Version
}

// GetServer6VersionOk returns a tuple with the Server6Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6VersionOk() (*string, bool) {
	if o == nil || o.Server6Version == nil {
		return nil, false
	}
	return o.Server6Version, true
}

// HasServer6Version returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6Version() bool {
	if o != nil && o.Server6Version != nil {
		return true
	}

	return false
}

// SetServer6Version gets a reference to the given string and assigns it to the Server6Version field.
func (o *DhcpServer6DataData) SetServer6Version(v string) {
	o.Server6Version = &v
}

// GetServer6Addr returns the Server6Addr field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6Addr() string {
	if o == nil || o.Server6Addr == nil {
		var ret string
		return ret
	}
	return *o.Server6Addr
}

// GetServer6AddrOk returns a tuple with the Server6Addr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6AddrOk() (*string, bool) {
	if o == nil || o.Server6Addr == nil {
		return nil, false
	}
	return o.Server6Addr, true
}

// HasServer6Addr returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6Addr() bool {
	if o != nil && o.Server6Addr != nil {
		return true
	}

	return false
}

// SetServer6Addr gets a reference to the given string and assigns it to the Server6Addr field.
func (o *DhcpServer6DataData) SetServer6Addr(v string) {
	o.Server6Addr = &v
}

// GetServer6HttpsLogin returns the Server6HttpsLogin field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6HttpsLogin() string {
	if o == nil || o.Server6HttpsLogin == nil {
		var ret string
		return ret
	}
	return *o.Server6HttpsLogin
}

// GetServer6HttpsLoginOk returns a tuple with the Server6HttpsLogin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6HttpsLoginOk() (*string, bool) {
	if o == nil || o.Server6HttpsLogin == nil {
		return nil, false
	}
	return o.Server6HttpsLogin, true
}

// HasServer6HttpsLogin returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6HttpsLogin() bool {
	if o != nil && o.Server6HttpsLogin != nil {
		return true
	}

	return false
}

// SetServer6HttpsLogin gets a reference to the given string and assigns it to the Server6HttpsLogin field.
func (o *DhcpServer6DataData) SetServer6HttpsLogin(v string) {
	o.Server6HttpsLogin = &v
}

// GetServer6IsPackage returns the Server6IsPackage field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6IsPackage() string {
	if o == nil || o.Server6IsPackage == nil {
		var ret string
		return ret
	}
	return *o.Server6IsPackage
}

// GetServer6IsPackageOk returns a tuple with the Server6IsPackage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6IsPackageOk() (*string, bool) {
	if o == nil || o.Server6IsPackage == nil {
		return nil, false
	}
	return o.Server6IsPackage, true
}

// HasServer6IsPackage returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6IsPackage() bool {
	if o != nil && o.Server6IsPackage != nil {
		return true
	}

	return false
}

// SetServer6IsPackage gets a reference to the given string and assigns it to the Server6IsPackage field.
func (o *DhcpServer6DataData) SetServer6IsPackage(v string) {
	o.Server6IsPackage = &v
}

// GetServer6Isolated returns the Server6Isolated field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6Isolated() string {
	if o == nil || o.Server6Isolated == nil {
		var ret string
		return ret
	}
	return *o.Server6Isolated
}

// GetServer6IsolatedOk returns a tuple with the Server6Isolated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6IsolatedOk() (*string, bool) {
	if o == nil || o.Server6Isolated == nil {
		return nil, false
	}
	return o.Server6Isolated, true
}

// HasServer6Isolated returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6Isolated() bool {
	if o != nil && o.Server6Isolated != nil {
		return true
	}

	return false
}

// SetServer6Isolated gets a reference to the given string and assigns it to the Server6Isolated field.
func (o *DhcpServer6DataData) SetServer6Isolated(v string) {
	o.Server6Isolated = &v
}

// GetServer6Multistatus returns the Server6Multistatus field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6Multistatus() string {
	if o == nil || o.Server6Multistatus == nil {
		var ret string
		return ret
	}
	return *o.Server6Multistatus
}

// GetServer6MultistatusOk returns a tuple with the Server6Multistatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6MultistatusOk() (*string, bool) {
	if o == nil || o.Server6Multistatus == nil {
		return nil, false
	}
	return o.Server6Multistatus, true
}

// HasServer6Multistatus returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6Multistatus() bool {
	if o != nil && o.Server6Multistatus != nil {
		return true
	}

	return false
}

// SetServer6Multistatus gets a reference to the given string and assigns it to the Server6Multistatus field.
func (o *DhcpServer6DataData) SetServer6Multistatus(v string) {
	o.Server6Multistatus = &v
}

// GetReverseProxyConf returns the ReverseProxyConf field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetReverseProxyConf() string {
	if o == nil || o.ReverseProxyConf == nil {
		var ret string
		return ret
	}
	return *o.ReverseProxyConf
}

// GetReverseProxyConfOk returns a tuple with the ReverseProxyConf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetReverseProxyConfOk() (*string, bool) {
	if o == nil || o.ReverseProxyConf == nil {
		return nil, false
	}
	return o.ReverseProxyConf, true
}

// HasReverseProxyConf returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasReverseProxyConf() bool {
	if o != nil && o.ReverseProxyConf != nil {
		return true
	}

	return false
}

// SetReverseProxyConf gets a reference to the given string and assigns it to the ReverseProxyConf field.
func (o *DhcpServer6DataData) SetReverseProxyConf(v string) {
	o.ReverseProxyConf = &v
}

// GetServer6SnmpId returns the Server6SnmpId field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6SnmpId() string {
	if o == nil || o.Server6SnmpId == nil {
		var ret string
		return ret
	}
	return *o.Server6SnmpId
}

// GetServer6SnmpIdOk returns a tuple with the Server6SnmpId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6SnmpIdOk() (*string, bool) {
	if o == nil || o.Server6SnmpId == nil {
		return nil, false
	}
	return o.Server6SnmpId, true
}

// HasServer6SnmpId returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6SnmpId() bool {
	if o != nil && o.Server6SnmpId != nil {
		return true
	}

	return false
}

// SetServer6SnmpId gets a reference to the given string and assigns it to the Server6SnmpId field.
func (o *DhcpServer6DataData) SetServer6SnmpId(v string) {
	o.Server6SnmpId = &v
}

// GetServer6SnmpPort returns the Server6SnmpPort field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6SnmpPort() string {
	if o == nil || o.Server6SnmpPort == nil {
		var ret string
		return ret
	}
	return *o.Server6SnmpPort
}

// GetServer6SnmpPortOk returns a tuple with the Server6SnmpPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6SnmpPortOk() (*string, bool) {
	if o == nil || o.Server6SnmpPort == nil {
		return nil, false
	}
	return o.Server6SnmpPort, true
}

// HasServer6SnmpPort returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6SnmpPort() bool {
	if o != nil && o.Server6SnmpPort != nil {
		return true
	}

	return false
}

// SetServer6SnmpPort gets a reference to the given string and assigns it to the Server6SnmpPort field.
func (o *DhcpServer6DataData) SetServer6SnmpPort(v string) {
	o.Server6SnmpPort = &v
}

// GetServer6SnmpProfileId returns the Server6SnmpProfileId field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6SnmpProfileId() string {
	if o == nil || o.Server6SnmpProfileId == nil {
		var ret string
		return ret
	}
	return *o.Server6SnmpProfileId
}

// GetServer6SnmpProfileIdOk returns a tuple with the Server6SnmpProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6SnmpProfileIdOk() (*string, bool) {
	if o == nil || o.Server6SnmpProfileId == nil {
		return nil, false
	}
	return o.Server6SnmpProfileId, true
}

// HasServer6SnmpProfileId returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6SnmpProfileId() bool {
	if o != nil && o.Server6SnmpProfileId != nil {
		return true
	}

	return false
}

// SetServer6SnmpProfileId gets a reference to the given string and assigns it to the Server6SnmpProfileId field.
func (o *DhcpServer6DataData) SetServer6SnmpProfileId(v string) {
	o.Server6SnmpProfileId = &v
}

// GetServer6SnmpRetry returns the Server6SnmpRetry field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6SnmpRetry() string {
	if o == nil || o.Server6SnmpRetry == nil {
		var ret string
		return ret
	}
	return *o.Server6SnmpRetry
}

// GetServer6SnmpRetryOk returns a tuple with the Server6SnmpRetry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6SnmpRetryOk() (*string, bool) {
	if o == nil || o.Server6SnmpRetry == nil {
		return nil, false
	}
	return o.Server6SnmpRetry, true
}

// HasServer6SnmpRetry returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6SnmpRetry() bool {
	if o != nil && o.Server6SnmpRetry != nil {
		return true
	}

	return false
}

// SetServer6SnmpRetry gets a reference to the given string and assigns it to the Server6SnmpRetry field.
func (o *DhcpServer6DataData) SetServer6SnmpRetry(v string) {
	o.Server6SnmpRetry = &v
}

// GetServer6SnmpTimeout returns the Server6SnmpTimeout field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6SnmpTimeout() string {
	if o == nil || o.Server6SnmpTimeout == nil {
		var ret string
		return ret
	}
	return *o.Server6SnmpTimeout
}

// GetServer6SnmpTimeoutOk returns a tuple with the Server6SnmpTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6SnmpTimeoutOk() (*string, bool) {
	if o == nil || o.Server6SnmpTimeout == nil {
		return nil, false
	}
	return o.Server6SnmpTimeout, true
}

// HasServer6SnmpTimeout returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6SnmpTimeout() bool {
	if o != nil && o.Server6SnmpTimeout != nil {
		return true
	}

	return false
}

// SetServer6SnmpTimeout gets a reference to the given string and assigns it to the Server6SnmpTimeout field.
func (o *DhcpServer6DataData) SetServer6SnmpTimeout(v string) {
	o.Server6SnmpTimeout = &v
}

// GetServer6SnmpUseTcp returns the Server6SnmpUseTcp field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6SnmpUseTcp() string {
	if o == nil || o.Server6SnmpUseTcp == nil {
		var ret string
		return ret
	}
	return *o.Server6SnmpUseTcp
}

// GetServer6SnmpUseTcpOk returns a tuple with the Server6SnmpUseTcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6SnmpUseTcpOk() (*string, bool) {
	if o == nil || o.Server6SnmpUseTcp == nil {
		return nil, false
	}
	return o.Server6SnmpUseTcp, true
}

// HasServer6SnmpUseTcp returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6SnmpUseTcp() bool {
	if o != nil && o.Server6SnmpUseTcp != nil {
		return true
	}

	return false
}

// SetServer6SnmpUseTcp gets a reference to the given string and assigns it to the Server6SnmpUseTcp field.
func (o *DhcpServer6DataData) SetServer6SnmpUseTcp(v string) {
	o.Server6SnmpUseTcp = &v
}

// GetServer6StatEnabled returns the Server6StatEnabled field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6StatEnabled() string {
	if o == nil || o.Server6StatEnabled == nil {
		var ret string
		return ret
	}
	return *o.Server6StatEnabled
}

// GetServer6StatEnabledOk returns a tuple with the Server6StatEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6StatEnabledOk() (*string, bool) {
	if o == nil || o.Server6StatEnabled == nil {
		return nil, false
	}
	return o.Server6StatEnabled, true
}

// HasServer6StatEnabled returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6StatEnabled() bool {
	if o != nil && o.Server6StatEnabled != nil {
		return true
	}

	return false
}

// SetServer6StatEnabled gets a reference to the given string and assigns it to the Server6StatEnabled field.
func (o *DhcpServer6DataData) SetServer6StatEnabled(v string) {
	o.Server6StatEnabled = &v
}

// GetServer6StatNiceness returns the Server6StatNiceness field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6StatNiceness() string {
	if o == nil || o.Server6StatNiceness == nil {
		var ret string
		return ret
	}
	return *o.Server6StatNiceness
}

// GetServer6StatNicenessOk returns a tuple with the Server6StatNiceness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6StatNicenessOk() (*string, bool) {
	if o == nil || o.Server6StatNiceness == nil {
		return nil, false
	}
	return o.Server6StatNiceness, true
}

// HasServer6StatNiceness returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6StatNiceness() bool {
	if o != nil && o.Server6StatNiceness != nil {
		return true
	}

	return false
}

// SetServer6StatNiceness gets a reference to the given string and assigns it to the Server6StatNiceness field.
func (o *DhcpServer6DataData) SetServer6StatNiceness(v string) {
	o.Server6StatNiceness = &v
}

// GetServer6StatPeriod returns the Server6StatPeriod field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6StatPeriod() string {
	if o == nil || o.Server6StatPeriod == nil {
		var ret string
		return ret
	}
	return *o.Server6StatPeriod
}

// GetServer6StatPeriodOk returns a tuple with the Server6StatPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6StatPeriodOk() (*string, bool) {
	if o == nil || o.Server6StatPeriod == nil {
		return nil, false
	}
	return o.Server6StatPeriod, true
}

// HasServer6StatPeriod returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6StatPeriod() bool {
	if o != nil && o.Server6StatPeriod != nil {
		return true
	}

	return false
}

// SetServer6StatPeriod gets a reference to the given string and assigns it to the Server6StatPeriod field.
func (o *DhcpServer6DataData) SetServer6StatPeriod(v string) {
	o.Server6StatPeriod = &v
}

// GetServer6StatTime returns the Server6StatTime field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetServer6StatTime() string {
	if o == nil || o.Server6StatTime == nil {
		var ret string
		return ret
	}
	return *o.Server6StatTime
}

// GetServer6StatTimeOk returns a tuple with the Server6StatTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetServer6StatTimeOk() (*string, bool) {
	if o == nil || o.Server6StatTime == nil {
		return nil, false
	}
	return o.Server6StatTime, true
}

// HasServer6StatTime returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasServer6StatTime() bool {
	if o != nil && o.Server6StatTime != nil {
		return true
	}

	return false
}

// SetServer6StatTime gets a reference to the given string and assigns it to the Server6StatTime field.
func (o *DhcpServer6DataData) SetServer6StatTime(v string) {
	o.Server6StatTime = &v
}

// GetTotalSmartMembers returns the TotalSmartMembers field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetTotalSmartMembers() string {
	if o == nil || o.TotalSmartMembers == nil {
		var ret string
		return ret
	}
	return *o.TotalSmartMembers
}

// GetTotalSmartMembersOk returns a tuple with the TotalSmartMembers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetTotalSmartMembersOk() (*string, bool) {
	if o == nil || o.TotalSmartMembers == nil {
		return nil, false
	}
	return o.TotalSmartMembers, true
}

// HasTotalSmartMembers returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasTotalSmartMembers() bool {
	if o != nil && o.TotalSmartMembers != nil {
		return true
	}

	return false
}

// SetTotalSmartMembers gets a reference to the given string and assigns it to the TotalSmartMembers field.
func (o *DhcpServer6DataData) SetTotalSmartMembers(v string) {
	o.TotalSmartMembers = &v
}

// GetSmartArch returns the SmartArch field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetSmartArch() string {
	if o == nil || o.SmartArch == nil {
		var ret string
		return ret
	}
	return *o.SmartArch
}

// GetSmartArchOk returns a tuple with the SmartArch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetSmartArchOk() (*string, bool) {
	if o == nil || o.SmartArch == nil {
		return nil, false
	}
	return o.SmartArch, true
}

// HasSmartArch returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasSmartArch() bool {
	if o != nil && o.SmartArch != nil {
		return true
	}

	return false
}

// SetSmartArch gets a reference to the given string and assigns it to the SmartArch field.
func (o *DhcpServer6DataData) SetSmartArch(v string) {
	o.SmartArch = &v
}

// GetSmartMembersName returns the SmartMembersName field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetSmartMembersName() string {
	if o == nil || o.SmartMembersName == nil {
		var ret string
		return ret
	}
	return *o.SmartMembersName
}

// GetSmartMembersNameOk returns a tuple with the SmartMembersName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetSmartMembersNameOk() (*string, bool) {
	if o == nil || o.SmartMembersName == nil {
		return nil, false
	}
	return o.SmartMembersName, true
}

// HasSmartMembersName returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasSmartMembersName() bool {
	if o != nil && o.SmartMembersName != nil {
		return true
	}

	return false
}

// SetSmartMembersName gets a reference to the given string and assigns it to the SmartMembersName field.
func (o *DhcpServer6DataData) SetSmartMembersName(v string) {
	o.SmartMembersName = &v
}

// GetSmartParam1 returns the SmartParam1 field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetSmartParam1() string {
	if o == nil || o.SmartParam1 == nil {
		var ret string
		return ret
	}
	return *o.SmartParam1
}

// GetSmartParam1Ok returns a tuple with the SmartParam1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetSmartParam1Ok() (*string, bool) {
	if o == nil || o.SmartParam1 == nil {
		return nil, false
	}
	return o.SmartParam1, true
}

// HasSmartParam1 returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasSmartParam1() bool {
	if o != nil && o.SmartParam1 != nil {
		return true
	}

	return false
}

// SetSmartParam1 gets a reference to the given string and assigns it to the SmartParam1 field.
func (o *DhcpServer6DataData) SetSmartParam1(v string) {
	o.SmartParam1 = &v
}

// GetSmartParentArch returns the SmartParentArch field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetSmartParentArch() string {
	if o == nil || o.SmartParentArch == nil {
		var ret string
		return ret
	}
	return *o.SmartParentArch
}

// GetSmartParentArchOk returns a tuple with the SmartParentArch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetSmartParentArchOk() (*string, bool) {
	if o == nil || o.SmartParentArch == nil {
		return nil, false
	}
	return o.SmartParentArch, true
}

// HasSmartParentArch returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasSmartParentArch() bool {
	if o != nil && o.SmartParentArch != nil {
		return true
	}

	return false
}

// SetSmartParentArch gets a reference to the given string and assigns it to the SmartParentArch field.
func (o *DhcpServer6DataData) SetSmartParentArch(v string) {
	o.SmartParentArch = &v
}

// GetSmartParentId returns the SmartParentId field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetSmartParentId() string {
	if o == nil || o.SmartParentId == nil {
		var ret string
		return ret
	}
	return *o.SmartParentId
}

// GetSmartParentIdOk returns a tuple with the SmartParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetSmartParentIdOk() (*string, bool) {
	if o == nil || o.SmartParentId == nil {
		return nil, false
	}
	return o.SmartParentId, true
}

// HasSmartParentId returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasSmartParentId() bool {
	if o != nil && o.SmartParentId != nil {
		return true
	}

	return false
}

// SetSmartParentId gets a reference to the given string and assigns it to the SmartParentId field.
func (o *DhcpServer6DataData) SetSmartParentId(v string) {
	o.SmartParentId = &v
}

// GetSmartParentName returns the SmartParentName field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetSmartParentName() string {
	if o == nil || o.SmartParentName == nil {
		var ret string
		return ret
	}
	return *o.SmartParentName
}

// GetSmartParentNameOk returns a tuple with the SmartParentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetSmartParentNameOk() (*string, bool) {
	if o == nil || o.SmartParentName == nil {
		return nil, false
	}
	return o.SmartParentName, true
}

// HasSmartParentName returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasSmartParentName() bool {
	if o != nil && o.SmartParentName != nil {
		return true
	}

	return false
}

// SetSmartParentName gets a reference to the given string and assigns it to the SmartParentName field.
func (o *DhcpServer6DataData) SetSmartParentName(v string) {
	o.SmartParentName = &v
}

// GetSmartRef1Server6Id returns the SmartRef1Server6Id field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetSmartRef1Server6Id() string {
	if o == nil || o.SmartRef1Server6Id == nil {
		var ret string
		return ret
	}
	return *o.SmartRef1Server6Id
}

// GetSmartRef1Server6IdOk returns a tuple with the SmartRef1Server6Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetSmartRef1Server6IdOk() (*string, bool) {
	if o == nil || o.SmartRef1Server6Id == nil {
		return nil, false
	}
	return o.SmartRef1Server6Id, true
}

// HasSmartRef1Server6Id returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasSmartRef1Server6Id() bool {
	if o != nil && o.SmartRef1Server6Id != nil {
		return true
	}

	return false
}

// SetSmartRef1Server6Id gets a reference to the given string and assigns it to the SmartRef1Server6Id field.
func (o *DhcpServer6DataData) SetSmartRef1Server6Id(v string) {
	o.SmartRef1Server6Id = &v
}

// GetSmartRef1Server6Name returns the SmartRef1Server6Name field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetSmartRef1Server6Name() string {
	if o == nil || o.SmartRef1Server6Name == nil {
		var ret string
		return ret
	}
	return *o.SmartRef1Server6Name
}

// GetSmartRef1Server6NameOk returns a tuple with the SmartRef1Server6Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetSmartRef1Server6NameOk() (*string, bool) {
	if o == nil || o.SmartRef1Server6Name == nil {
		return nil, false
	}
	return o.SmartRef1Server6Name, true
}

// HasSmartRef1Server6Name returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasSmartRef1Server6Name() bool {
	if o != nil && o.SmartRef1Server6Name != nil {
		return true
	}

	return false
}

// SetSmartRef1Server6Name gets a reference to the given string and assigns it to the SmartRef1Server6Name field.
func (o *DhcpServer6DataData) SetSmartRef1Server6Name(v string) {
	o.SmartRef1Server6Name = &v
}

// GetSmartRef2Server6Id returns the SmartRef2Server6Id field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetSmartRef2Server6Id() string {
	if o == nil || o.SmartRef2Server6Id == nil {
		var ret string
		return ret
	}
	return *o.SmartRef2Server6Id
}

// GetSmartRef2Server6IdOk returns a tuple with the SmartRef2Server6Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetSmartRef2Server6IdOk() (*string, bool) {
	if o == nil || o.SmartRef2Server6Id == nil {
		return nil, false
	}
	return o.SmartRef2Server6Id, true
}

// HasSmartRef2Server6Id returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasSmartRef2Server6Id() bool {
	if o != nil && o.SmartRef2Server6Id != nil {
		return true
	}

	return false
}

// SetSmartRef2Server6Id gets a reference to the given string and assigns it to the SmartRef2Server6Id field.
func (o *DhcpServer6DataData) SetSmartRef2Server6Id(v string) {
	o.SmartRef2Server6Id = &v
}

// GetSmartRef2Server6Name returns the SmartRef2Server6Name field value if set, zero value otherwise.
func (o *DhcpServer6DataData) GetSmartRef2Server6Name() string {
	if o == nil || o.SmartRef2Server6Name == nil {
		var ret string
		return ret
	}
	return *o.SmartRef2Server6Name
}

// GetSmartRef2Server6NameOk returns a tuple with the SmartRef2Server6Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DhcpServer6DataData) GetSmartRef2Server6NameOk() (*string, bool) {
	if o == nil || o.SmartRef2Server6Name == nil {
		return nil, false
	}
	return o.SmartRef2Server6Name, true
}

// HasSmartRef2Server6Name returns a boolean if a field has been set.
func (o *DhcpServer6DataData) HasSmartRef2Server6Name() bool {
	if o != nil && o.SmartRef2Server6Name != nil {
		return true
	}

	return false
}

// SetSmartRef2Server6Name gets a reference to the given string and assigns it to the SmartRef2Server6Name field.
func (o *DhcpServer6DataData) SetSmartRef2Server6Name(v string) {
	o.SmartRef2Server6Name = &v
}

func (o DhcpServer6DataData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Server6ClassName != nil {
		toSerialize["server6_class_name"] = o.Server6ClassName
	}
	if o.Server6ClassParameters != nil {
		toSerialize["server6_class_parameters"] = o.Server6ClassParameters
	}
	if o.Server6Comment != nil {
		toSerialize["server6_comment"] = o.Server6Comment
	}
	if o.Server6Id != nil {
		toSerialize["server6_id"] = o.Server6Id
	}
	if o.Server6LastRefreshTime != nil {
		toSerialize["server6_last_refresh_time"] = o.Server6LastRefreshTime
	}
	if o.Server6Name != nil {
		toSerialize["server6_name"] = o.Server6Name
	}
	if o.Server6State != nil {
		toSerialize["server6_state"] = o.Server6State
	}
	if o.Server6Synching != nil {
		toSerialize["server6_synching"] = o.Server6Synching
	}
	if o.Server6Type != nil {
		toSerialize["server6_type"] = o.Server6Type
	}
	if o.Server6Uboottime != nil {
		toSerialize["server6_uboottime"] = o.Server6Uboottime
	}
	if o.Server6Version != nil {
		toSerialize["server6_version"] = o.Server6Version
	}
	if o.Server6Addr != nil {
		toSerialize["server6_addr"] = o.Server6Addr
	}
	if o.Server6HttpsLogin != nil {
		toSerialize["server6_https_login"] = o.Server6HttpsLogin
	}
	if o.Server6IsPackage != nil {
		toSerialize["server6_is_package"] = o.Server6IsPackage
	}
	if o.Server6Isolated != nil {
		toSerialize["server6_isolated"] = o.Server6Isolated
	}
	if o.Server6Multistatus != nil {
		toSerialize["server6_multistatus"] = o.Server6Multistatus
	}
	if o.ReverseProxyConf != nil {
		toSerialize["reverse_proxy_conf"] = o.ReverseProxyConf
	}
	if o.Server6SnmpId != nil {
		toSerialize["server6_snmp_id"] = o.Server6SnmpId
	}
	if o.Server6SnmpPort != nil {
		toSerialize["server6_snmp_port"] = o.Server6SnmpPort
	}
	if o.Server6SnmpProfileId != nil {
		toSerialize["server6_snmp_profile_id"] = o.Server6SnmpProfileId
	}
	if o.Server6SnmpRetry != nil {
		toSerialize["server6_snmp_retry"] = o.Server6SnmpRetry
	}
	if o.Server6SnmpTimeout != nil {
		toSerialize["server6_snmp_timeout"] = o.Server6SnmpTimeout
	}
	if o.Server6SnmpUseTcp != nil {
		toSerialize["server6_snmp_use_tcp"] = o.Server6SnmpUseTcp
	}
	if o.Server6StatEnabled != nil {
		toSerialize["server6_stat_enabled"] = o.Server6StatEnabled
	}
	if o.Server6StatNiceness != nil {
		toSerialize["server6_stat_niceness"] = o.Server6StatNiceness
	}
	if o.Server6StatPeriod != nil {
		toSerialize["server6_stat_period"] = o.Server6StatPeriod
	}
	if o.Server6StatTime != nil {
		toSerialize["server6_stat_time"] = o.Server6StatTime
	}
	if o.TotalSmartMembers != nil {
		toSerialize["total_smart_members"] = o.TotalSmartMembers
	}
	if o.SmartArch != nil {
		toSerialize["smart_arch"] = o.SmartArch
	}
	if o.SmartMembersName != nil {
		toSerialize["smart_members_name"] = o.SmartMembersName
	}
	if o.SmartParam1 != nil {
		toSerialize["smart_param1"] = o.SmartParam1
	}
	if o.SmartParentArch != nil {
		toSerialize["smart_parent_arch"] = o.SmartParentArch
	}
	if o.SmartParentId != nil {
		toSerialize["smart_parent_id"] = o.SmartParentId
	}
	if o.SmartParentName != nil {
		toSerialize["smart_parent_name"] = o.SmartParentName
	}
	if o.SmartRef1Server6Id != nil {
		toSerialize["smart_ref1_server6_id"] = o.SmartRef1Server6Id
	}
	if o.SmartRef1Server6Name != nil {
		toSerialize["smart_ref1_server6_name"] = o.SmartRef1Server6Name
	}
	if o.SmartRef2Server6Id != nil {
		toSerialize["smart_ref2_server6_id"] = o.SmartRef2Server6Id
	}
	if o.SmartRef2Server6Name != nil {
		toSerialize["smart_ref2_server6_name"] = o.SmartRef2Server6Name
	}
	return json.Marshal(toSerialize)
}

type NullableDhcpServer6DataData struct {
	value *DhcpServer6DataData
	isSet bool
}

func (v NullableDhcpServer6DataData) Get() *DhcpServer6DataData {
	return v.value
}

func (v *NullableDhcpServer6DataData) Set(val *DhcpServer6DataData) {
	v.value = val
	v.isSet = true
}

func (v NullableDhcpServer6DataData) IsSet() bool {
	return v.isSet
}

func (v *NullableDhcpServer6DataData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDhcpServer6DataData(val *DhcpServer6DataData) *NullableDhcpServer6DataData {
	return &NullableDhcpServer6DataData{value: val, isSet: true}
}

func (v NullableDhcpServer6DataData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDhcpServer6DataData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


