/*
 * SOLIDserver API
 *
 * OpenAPI 3.0.2 API definition for SOLIDserver service from EfficientIP.<p>Copyright © 2000-2021 EfficientIP</p><p><em>All specifications and information regarding the products in  this document are subject to change without notice and should not be  construed as a commitment by EfficientIP. EfficientIP assumes no  responsibility or liability for any mistakes or inaccuracies that may appear  in this document. All statements and recommendations in this document are  believed to be accurate but are presented without warranty. Users must take  full responsibility for their application of any product.</em></p><p>Generated (Monday 14th of June 2021 12:30:34 PM)</p>
 *
 * API version: 2.0
 * Contact: support-api@efficientip.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdsclient

import (
	"encoding/json"
)

// GuardianPolicyEditInput struct for GuardianPolicyEditInput
type GuardianPolicyEditInput struct {
	// The database identifier (ID) of the policy, a unique identifier automatically incremented when you add the policy. Use it to identify the policy of your choice.
	PolicyId *int32 `json:"policy_id,omitempty"`
	// The name of the policy.
	PolicyName *string `json:"policy_name,omitempty"`
	// The description of the policy.
	Description *string `json:"description,omitempty"`
	// The name of all the Guardian servers associated with the policy. You can specify one or more names.
	ServerList *string `json:"server_list,omitempty"`
	// A way to bypass <b>(accept) </b>any enabled rule that would return warning messages. If the service returns an error message, you cannot bypass the enabled rules.
	Warnings *string `json:"warnings,omitempty"`
}

// NewGuardianPolicyEditInput instantiates a new GuardianPolicyEditInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuardianPolicyEditInput() *GuardianPolicyEditInput {
	this := GuardianPolicyEditInput{}
	return &this
}

// NewGuardianPolicyEditInputWithDefaults instantiates a new GuardianPolicyEditInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuardianPolicyEditInputWithDefaults() *GuardianPolicyEditInput {
	this := GuardianPolicyEditInput{}
	return &this
}

// GetPolicyId returns the PolicyId field value if set, zero value otherwise.
func (o *GuardianPolicyEditInput) GetPolicyId() int32 {
	if o == nil || o.PolicyId == nil {
		var ret int32
		return ret
	}
	return *o.PolicyId
}

// GetPolicyIdOk returns a tuple with the PolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuardianPolicyEditInput) GetPolicyIdOk() (*int32, bool) {
	if o == nil || o.PolicyId == nil {
		return nil, false
	}
	return o.PolicyId, true
}

// HasPolicyId returns a boolean if a field has been set.
func (o *GuardianPolicyEditInput) HasPolicyId() bool {
	if o != nil && o.PolicyId != nil {
		return true
	}

	return false
}

// SetPolicyId gets a reference to the given int32 and assigns it to the PolicyId field.
func (o *GuardianPolicyEditInput) SetPolicyId(v int32) {
	o.PolicyId = &v
}

// GetPolicyName returns the PolicyName field value if set, zero value otherwise.
func (o *GuardianPolicyEditInput) GetPolicyName() string {
	if o == nil || o.PolicyName == nil {
		var ret string
		return ret
	}
	return *o.PolicyName
}

// GetPolicyNameOk returns a tuple with the PolicyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuardianPolicyEditInput) GetPolicyNameOk() (*string, bool) {
	if o == nil || o.PolicyName == nil {
		return nil, false
	}
	return o.PolicyName, true
}

// HasPolicyName returns a boolean if a field has been set.
func (o *GuardianPolicyEditInput) HasPolicyName() bool {
	if o != nil && o.PolicyName != nil {
		return true
	}

	return false
}

// SetPolicyName gets a reference to the given string and assigns it to the PolicyName field.
func (o *GuardianPolicyEditInput) SetPolicyName(v string) {
	o.PolicyName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GuardianPolicyEditInput) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuardianPolicyEditInput) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GuardianPolicyEditInput) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GuardianPolicyEditInput) SetDescription(v string) {
	o.Description = &v
}

// GetServerList returns the ServerList field value if set, zero value otherwise.
func (o *GuardianPolicyEditInput) GetServerList() string {
	if o == nil || o.ServerList == nil {
		var ret string
		return ret
	}
	return *o.ServerList
}

// GetServerListOk returns a tuple with the ServerList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuardianPolicyEditInput) GetServerListOk() (*string, bool) {
	if o == nil || o.ServerList == nil {
		return nil, false
	}
	return o.ServerList, true
}

// HasServerList returns a boolean if a field has been set.
func (o *GuardianPolicyEditInput) HasServerList() bool {
	if o != nil && o.ServerList != nil {
		return true
	}

	return false
}

// SetServerList gets a reference to the given string and assigns it to the ServerList field.
func (o *GuardianPolicyEditInput) SetServerList(v string) {
	o.ServerList = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *GuardianPolicyEditInput) GetWarnings() string {
	if o == nil || o.Warnings == nil {
		var ret string
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuardianPolicyEditInput) GetWarningsOk() (*string, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *GuardianPolicyEditInput) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given string and assigns it to the Warnings field.
func (o *GuardianPolicyEditInput) SetWarnings(v string) {
	o.Warnings = &v
}

func (o GuardianPolicyEditInput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PolicyId != nil {
		toSerialize["policy_id"] = o.PolicyId
	}
	if o.PolicyName != nil {
		toSerialize["policy_name"] = o.PolicyName
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.ServerList != nil {
		toSerialize["server_list"] = o.ServerList
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableGuardianPolicyEditInput struct {
	value *GuardianPolicyEditInput
	isSet bool
}

func (v NullableGuardianPolicyEditInput) Get() *GuardianPolicyEditInput {
	return v.value
}

func (v *NullableGuardianPolicyEditInput) Set(val *GuardianPolicyEditInput) {
	v.value = val
	v.isSet = true
}

func (v NullableGuardianPolicyEditInput) IsSet() bool {
	return v.isSet
}

func (v *NullableGuardianPolicyEditInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuardianPolicyEditInput(val *GuardianPolicyEditInput) *NullableGuardianPolicyEditInput {
	return &NullableGuardianPolicyEditInput{value: val, isSet: true}
}

func (v NullableGuardianPolicyEditInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuardianPolicyEditInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


