/*
SOLIDserver API

OpenAPI 3.0.2 API definition for SOLIDserver service from EfficientIP.<p>Copyright © 2000-2024 EfficientIP</p><p><em>All specifications and information regarding the products in this document are subject to change without notice and should not be construed as a commitment by EfficientIP. EfficientIP assumes no responsibility or liability for any mistakes or inaccuracies that may appear in this document. All statements and recommendations in this document are believed to be accurate but are presented without warranty. Users must take full responsibility for their application of any product.</em></p><p><em>This document aims at detailing EfficientIP proprietary solutions. As our solutions rely on several third-party products, created by other companies or organizations, it may redirect readers to third-party websites and documentation for further information. In such a case, EfficientIP cannot be liable or expected to provide said information on products they do maintain or created.</em></p><p>Generated (Friday 4th of October 2024 03:41:11 PM)</p>

API version: 2.0
Contact: support-api@efficientip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdsclient

import (
	"encoding/json"
)

// checks if the DataInnerDnsZoneDeleteSuccess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataInnerDnsZoneDeleteSuccess{}

// DataInnerDnsZoneDeleteSuccess struct for DataInnerDnsZoneDeleteSuccess
type DataInnerDnsZoneDeleteSuccess struct {
	// The database identifier (ID) of the object you deleted.
	ZoneId *string `json:"zone_id,omitempty"`
}

// NewDataInnerDnsZoneDeleteSuccess instantiates a new DataInnerDnsZoneDeleteSuccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataInnerDnsZoneDeleteSuccess() *DataInnerDnsZoneDeleteSuccess {
	this := DataInnerDnsZoneDeleteSuccess{}
	return &this
}

// NewDataInnerDnsZoneDeleteSuccessWithDefaults instantiates a new DataInnerDnsZoneDeleteSuccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataInnerDnsZoneDeleteSuccessWithDefaults() *DataInnerDnsZoneDeleteSuccess {
	this := DataInnerDnsZoneDeleteSuccess{}
	return &this
}

// GetZoneId returns the ZoneId field value if set, zero value otherwise.
func (o *DataInnerDnsZoneDeleteSuccess) GetZoneId() string {
	if o == nil || IsNil(o.ZoneId) {
		var ret string
		return ret
	}
	return *o.ZoneId
}

// GetZoneIdOk returns a tuple with the ZoneId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataInnerDnsZoneDeleteSuccess) GetZoneIdOk() (*string, bool) {
	if o == nil || IsNil(o.ZoneId) {
		return nil, false
	}
	return o.ZoneId, true
}

// HasZoneId returns a boolean if a field has been set.
func (o *DataInnerDnsZoneDeleteSuccess) HasZoneId() bool {
	if o != nil && !IsNil(o.ZoneId) {
		return true
	}

	return false
}

// SetZoneId gets a reference to the given string and assigns it to the ZoneId field.
func (o *DataInnerDnsZoneDeleteSuccess) SetZoneId(v string) {
	o.ZoneId = &v
}

func (o DataInnerDnsZoneDeleteSuccess) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataInnerDnsZoneDeleteSuccess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ZoneId) {
		toSerialize["zone_id"] = o.ZoneId
	}
	return toSerialize, nil
}

type NullableDataInnerDnsZoneDeleteSuccess struct {
	value *DataInnerDnsZoneDeleteSuccess
	isSet bool
}

func (v NullableDataInnerDnsZoneDeleteSuccess) Get() *DataInnerDnsZoneDeleteSuccess {
	return v.value
}

func (v *NullableDataInnerDnsZoneDeleteSuccess) Set(val *DataInnerDnsZoneDeleteSuccess) {
	v.value = val
	v.isSet = true
}

func (v NullableDataInnerDnsZoneDeleteSuccess) IsSet() bool {
	return v.isSet
}

func (v *NullableDataInnerDnsZoneDeleteSuccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataInnerDnsZoneDeleteSuccess(val *DataInnerDnsZoneDeleteSuccess) *NullableDataInnerDnsZoneDeleteSuccess {
	return &NullableDataInnerDnsZoneDeleteSuccess{value: val, isSet: true}
}

func (v NullableDataInnerDnsZoneDeleteSuccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataInnerDnsZoneDeleteSuccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
