/*
SOLIDserver API

OpenAPI 3.0.2 API definition for SOLIDserver service from EfficientIP.<p>Copyright © 2000-2024 EfficientIP</p><p><em>All specifications and information regarding the products in this document are subject to change without notice and should not be construed as a commitment by EfficientIP. EfficientIP assumes no responsibility or liability for any mistakes or inaccuracies that may appear in this document. All statements and recommendations in this document are believed to be accurate but are presented without warranty. Users must take full responsibility for their application of any product.</em></p><p><em>This document aims at detailing EfficientIP proprietary solutions. As our solutions rely on several third-party products, created by other companies or organizations, it may redirect readers to third-party websites and documentation for further information. In such a case, EfficientIP cannot be liable or expected to provide said information on products they do maintain or created.</em></p><p>Generated (Friday 4th of October 2024 03:41:11 PM)</p>

API version: 2.0
Contact: support-api@efficientip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdsclient

import (
	"encoding/json"
)

// checks if the DataInnerIpamSpaceEditSuccess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataInnerIpamSpaceEditSuccess{}

// DataInnerIpamSpaceEditSuccess struct for DataInnerIpamSpaceEditSuccess
type DataInnerIpamSpaceEditSuccess struct {
	// The database identifier (ID) of the object you edited.
	SpaceId *string `json:"space_id,omitempty"`
}

// NewDataInnerIpamSpaceEditSuccess instantiates a new DataInnerIpamSpaceEditSuccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataInnerIpamSpaceEditSuccess() *DataInnerIpamSpaceEditSuccess {
	this := DataInnerIpamSpaceEditSuccess{}
	return &this
}

// NewDataInnerIpamSpaceEditSuccessWithDefaults instantiates a new DataInnerIpamSpaceEditSuccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataInnerIpamSpaceEditSuccessWithDefaults() *DataInnerIpamSpaceEditSuccess {
	this := DataInnerIpamSpaceEditSuccess{}
	return &this
}

// GetSpaceId returns the SpaceId field value if set, zero value otherwise.
func (o *DataInnerIpamSpaceEditSuccess) GetSpaceId() string {
	if o == nil || IsNil(o.SpaceId) {
		var ret string
		return ret
	}
	return *o.SpaceId
}

// GetSpaceIdOk returns a tuple with the SpaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataInnerIpamSpaceEditSuccess) GetSpaceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SpaceId) {
		return nil, false
	}
	return o.SpaceId, true
}

// HasSpaceId returns a boolean if a field has been set.
func (o *DataInnerIpamSpaceEditSuccess) HasSpaceId() bool {
	if o != nil && !IsNil(o.SpaceId) {
		return true
	}

	return false
}

// SetSpaceId gets a reference to the given string and assigns it to the SpaceId field.
func (o *DataInnerIpamSpaceEditSuccess) SetSpaceId(v string) {
	o.SpaceId = &v
}

func (o DataInnerIpamSpaceEditSuccess) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataInnerIpamSpaceEditSuccess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SpaceId) {
		toSerialize["space_id"] = o.SpaceId
	}
	return toSerialize, nil
}

type NullableDataInnerIpamSpaceEditSuccess struct {
	value *DataInnerIpamSpaceEditSuccess
	isSet bool
}

func (v NullableDataInnerIpamSpaceEditSuccess) Get() *DataInnerIpamSpaceEditSuccess {
	return v.value
}

func (v *NullableDataInnerIpamSpaceEditSuccess) Set(val *DataInnerIpamSpaceEditSuccess) {
	v.value = val
	v.isSet = true
}

func (v NullableDataInnerIpamSpaceEditSuccess) IsSet() bool {
	return v.isSet
}

func (v *NullableDataInnerIpamSpaceEditSuccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataInnerIpamSpaceEditSuccess(val *DataInnerIpamSpaceEditSuccess) *NullableDataInnerIpamSpaceEditSuccess {
	return &NullableDataInnerIpamSpaceEditSuccess{value: val, isSet: true}
}

func (v NullableDataInnerIpamSpaceEditSuccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataInnerIpamSpaceEditSuccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
