/*
 * SOLIDserver API
 *
 * OpenAPI 3.0.2 API definition for SOLIDserver service from EfficientIP.<p>Copyright © 2000-2021 EfficientIP</p><p><em>All specifications and information regarding the products in  this document are subject to change without notice and should not be  construed as a commitment by EfficientIP. EfficientIP assumes no  responsibility or liability for any mistakes or inaccuracies that may appear  in this document. All statements and recommendations in this document are  believed to be accurate but are presented without warranty. Users must take  full responsibility for their application of any product.</em></p><p>Generated (Monday 14th of June 2021 12:30:34 PM)</p>
 *
 * API version: 2.0
 * Contact: support-api@efficientip.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdsclient

import (
	"encoding/json"
)

// DnsViewAddInput struct for DnsViewAddInput
type DnsViewAddInput struct {
	// The database identifier (ID) of the DNS server, a unique numeric key value automatically incremented when you add a DNS server. Use the ID to specify the DNS server of your choice.
	ServerId *int32 `json:"server_id,omitempty"`
	// The name of the DNS server.
	ServerName *string `json:"server_name,omitempty"`
	// The name of the DNS view, each DNS view must have a unique name.
	ViewName *string `json:"view_name,omitempty"`
	// The IP address of the DNS server.
	ServerHostaddr *string `json:"server_hostaddr,omitempty"`
	// The ACL values associated with the allow-query configuration of the DNS view, as follows: <b>&lt;value1&gt;;&lt;value2&gt;;... </b>. Values may include IP and network addresses, the name of TSIG keys and ACLs, preceded by <b>!</b> if the access is denied.
	ViewAllowQuery *string `json:"view_allow_query,omitempty"`
	// The ACL values associated with the allow-recursion configuration of the DNS view, as follows: <b>&lt;value1&gt;;&lt;value2&gt;;... </b>. Values may include IP and network addresses, the name of TSIG keys and ACLs, preceded by <b>!</b> if the access is denied.
	ViewAllowRecursion *string `json:"view_allow_recursion,omitempty"`
	// The ACL values associated with the allow-transfer configuration of the DNS view, as follows: <b>&lt;value1&gt;;&lt;value2&gt;;... </b>. Values may include IP and network addresses, the name of TSIG keys and ACLs, preceded by <b>!</b> if the access is denied.
	ViewAllowTransfer *string `json:"view_allow_transfer,omitempty"`
	// The ACL values associated with the match clients configuration of the DNS view, as follows: <b>&lt;value1&gt;;&lt;value2&gt;;...</b> . Values may include IP and network addresses, the name of TSIG keys and ACLs, preceded by <b>!</b> if the access is denied.
	ViewMatchClients *string `json:"view_match_clients,omitempty"`
	// The ACL values associated with the match destination configuration of the DNS view, as follows: <b>&lt;value1&gt;;&lt;value2&gt;;...</b> . Values may include IP and network addresses, the name of TSIG keys and ACLs, preceded by <b>!</b> if the access is denied.
	ViewMatchTo *string `json:"view_match_to,omitempty"`
	// The level of the DNS view, where <b>0</b> represents the highest level in the views hierarchy. The parameters <b>dnsview_match_client</b> and <b>dnsview_match_to</b> of each view in a server are reviewed following this order.
	ViewOrder *int32 `json:"view_order,omitempty"`
	// The recursion status of the DNS view:<table><caption>dnsview_recursion possible values</caption><br/><thead><tr><th>Status</th><th>Description</th></tr><br/></thead><br/><tbody><tr><td >no</td><td >The view only provides iterative query behavior - normally resulting in a referral. If the answer to the query already exists in the cache it will be returned whatever the value of this statement.</td></tr><tr><td >yes</td><td >The view always provides recursive query behavior if requested by the client.</td></tr></tbody></table></p><br/>
	ViewRecursion *string `json:"view_recursion,omitempty"`
	// class parameters you want to delete from the object
	ClassParametersToDelete *[]string `json:"class_parameters_to_delete,omitempty"`
	// The name of the class to apply to the object you are adding. You must specify the class file directory, e.g. <b>my_directory/my_class.class</b> . You cannot use the classes <b>global</b> and <b>default</b>, they are reserved by the system.
	ViewClassName *string `json:"view_class_name,omitempty"`
	// class parameters in json format
	ViewClassParameters *[]ApiClassParameterInputEntry `json:"view_class_parameters,omitempty"`
	// A way to bypass <b>(accept) </b>any enabled rule that would return warning messages. If the service returns an error message, you cannot bypass the enabled rules.
	Warnings *string `json:"warnings,omitempty"`
}

// NewDnsViewAddInput instantiates a new DnsViewAddInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDnsViewAddInput() *DnsViewAddInput {
	this := DnsViewAddInput{}
	return &this
}

// NewDnsViewAddInputWithDefaults instantiates a new DnsViewAddInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDnsViewAddInputWithDefaults() *DnsViewAddInput {
	this := DnsViewAddInput{}
	return &this
}

// GetServerId returns the ServerId field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetServerId() int32 {
	if o == nil || o.ServerId == nil {
		var ret int32
		return ret
	}
	return *o.ServerId
}

// GetServerIdOk returns a tuple with the ServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetServerIdOk() (*int32, bool) {
	if o == nil || o.ServerId == nil {
		return nil, false
	}
	return o.ServerId, true
}

// HasServerId returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasServerId() bool {
	if o != nil && o.ServerId != nil {
		return true
	}

	return false
}

// SetServerId gets a reference to the given int32 and assigns it to the ServerId field.
func (o *DnsViewAddInput) SetServerId(v int32) {
	o.ServerId = &v
}

// GetServerName returns the ServerName field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetServerName() string {
	if o == nil || o.ServerName == nil {
		var ret string
		return ret
	}
	return *o.ServerName
}

// GetServerNameOk returns a tuple with the ServerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetServerNameOk() (*string, bool) {
	if o == nil || o.ServerName == nil {
		return nil, false
	}
	return o.ServerName, true
}

// HasServerName returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasServerName() bool {
	if o != nil && o.ServerName != nil {
		return true
	}

	return false
}

// SetServerName gets a reference to the given string and assigns it to the ServerName field.
func (o *DnsViewAddInput) SetServerName(v string) {
	o.ServerName = &v
}

// GetViewName returns the ViewName field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetViewName() string {
	if o == nil || o.ViewName == nil {
		var ret string
		return ret
	}
	return *o.ViewName
}

// GetViewNameOk returns a tuple with the ViewName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetViewNameOk() (*string, bool) {
	if o == nil || o.ViewName == nil {
		return nil, false
	}
	return o.ViewName, true
}

// HasViewName returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasViewName() bool {
	if o != nil && o.ViewName != nil {
		return true
	}

	return false
}

// SetViewName gets a reference to the given string and assigns it to the ViewName field.
func (o *DnsViewAddInput) SetViewName(v string) {
	o.ViewName = &v
}

// GetServerHostaddr returns the ServerHostaddr field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetServerHostaddr() string {
	if o == nil || o.ServerHostaddr == nil {
		var ret string
		return ret
	}
	return *o.ServerHostaddr
}

// GetServerHostaddrOk returns a tuple with the ServerHostaddr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetServerHostaddrOk() (*string, bool) {
	if o == nil || o.ServerHostaddr == nil {
		return nil, false
	}
	return o.ServerHostaddr, true
}

// HasServerHostaddr returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasServerHostaddr() bool {
	if o != nil && o.ServerHostaddr != nil {
		return true
	}

	return false
}

// SetServerHostaddr gets a reference to the given string and assigns it to the ServerHostaddr field.
func (o *DnsViewAddInput) SetServerHostaddr(v string) {
	o.ServerHostaddr = &v
}

// GetViewAllowQuery returns the ViewAllowQuery field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetViewAllowQuery() string {
	if o == nil || o.ViewAllowQuery == nil {
		var ret string
		return ret
	}
	return *o.ViewAllowQuery
}

// GetViewAllowQueryOk returns a tuple with the ViewAllowQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetViewAllowQueryOk() (*string, bool) {
	if o == nil || o.ViewAllowQuery == nil {
		return nil, false
	}
	return o.ViewAllowQuery, true
}

// HasViewAllowQuery returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasViewAllowQuery() bool {
	if o != nil && o.ViewAllowQuery != nil {
		return true
	}

	return false
}

// SetViewAllowQuery gets a reference to the given string and assigns it to the ViewAllowQuery field.
func (o *DnsViewAddInput) SetViewAllowQuery(v string) {
	o.ViewAllowQuery = &v
}

// GetViewAllowRecursion returns the ViewAllowRecursion field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetViewAllowRecursion() string {
	if o == nil || o.ViewAllowRecursion == nil {
		var ret string
		return ret
	}
	return *o.ViewAllowRecursion
}

// GetViewAllowRecursionOk returns a tuple with the ViewAllowRecursion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetViewAllowRecursionOk() (*string, bool) {
	if o == nil || o.ViewAllowRecursion == nil {
		return nil, false
	}
	return o.ViewAllowRecursion, true
}

// HasViewAllowRecursion returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasViewAllowRecursion() bool {
	if o != nil && o.ViewAllowRecursion != nil {
		return true
	}

	return false
}

// SetViewAllowRecursion gets a reference to the given string and assigns it to the ViewAllowRecursion field.
func (o *DnsViewAddInput) SetViewAllowRecursion(v string) {
	o.ViewAllowRecursion = &v
}

// GetViewAllowTransfer returns the ViewAllowTransfer field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetViewAllowTransfer() string {
	if o == nil || o.ViewAllowTransfer == nil {
		var ret string
		return ret
	}
	return *o.ViewAllowTransfer
}

// GetViewAllowTransferOk returns a tuple with the ViewAllowTransfer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetViewAllowTransferOk() (*string, bool) {
	if o == nil || o.ViewAllowTransfer == nil {
		return nil, false
	}
	return o.ViewAllowTransfer, true
}

// HasViewAllowTransfer returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasViewAllowTransfer() bool {
	if o != nil && o.ViewAllowTransfer != nil {
		return true
	}

	return false
}

// SetViewAllowTransfer gets a reference to the given string and assigns it to the ViewAllowTransfer field.
func (o *DnsViewAddInput) SetViewAllowTransfer(v string) {
	o.ViewAllowTransfer = &v
}

// GetViewMatchClients returns the ViewMatchClients field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetViewMatchClients() string {
	if o == nil || o.ViewMatchClients == nil {
		var ret string
		return ret
	}
	return *o.ViewMatchClients
}

// GetViewMatchClientsOk returns a tuple with the ViewMatchClients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetViewMatchClientsOk() (*string, bool) {
	if o == nil || o.ViewMatchClients == nil {
		return nil, false
	}
	return o.ViewMatchClients, true
}

// HasViewMatchClients returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasViewMatchClients() bool {
	if o != nil && o.ViewMatchClients != nil {
		return true
	}

	return false
}

// SetViewMatchClients gets a reference to the given string and assigns it to the ViewMatchClients field.
func (o *DnsViewAddInput) SetViewMatchClients(v string) {
	o.ViewMatchClients = &v
}

// GetViewMatchTo returns the ViewMatchTo field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetViewMatchTo() string {
	if o == nil || o.ViewMatchTo == nil {
		var ret string
		return ret
	}
	return *o.ViewMatchTo
}

// GetViewMatchToOk returns a tuple with the ViewMatchTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetViewMatchToOk() (*string, bool) {
	if o == nil || o.ViewMatchTo == nil {
		return nil, false
	}
	return o.ViewMatchTo, true
}

// HasViewMatchTo returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasViewMatchTo() bool {
	if o != nil && o.ViewMatchTo != nil {
		return true
	}

	return false
}

// SetViewMatchTo gets a reference to the given string and assigns it to the ViewMatchTo field.
func (o *DnsViewAddInput) SetViewMatchTo(v string) {
	o.ViewMatchTo = &v
}

// GetViewOrder returns the ViewOrder field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetViewOrder() int32 {
	if o == nil || o.ViewOrder == nil {
		var ret int32
		return ret
	}
	return *o.ViewOrder
}

// GetViewOrderOk returns a tuple with the ViewOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetViewOrderOk() (*int32, bool) {
	if o == nil || o.ViewOrder == nil {
		return nil, false
	}
	return o.ViewOrder, true
}

// HasViewOrder returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasViewOrder() bool {
	if o != nil && o.ViewOrder != nil {
		return true
	}

	return false
}

// SetViewOrder gets a reference to the given int32 and assigns it to the ViewOrder field.
func (o *DnsViewAddInput) SetViewOrder(v int32) {
	o.ViewOrder = &v
}

// GetViewRecursion returns the ViewRecursion field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetViewRecursion() string {
	if o == nil || o.ViewRecursion == nil {
		var ret string
		return ret
	}
	return *o.ViewRecursion
}

// GetViewRecursionOk returns a tuple with the ViewRecursion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetViewRecursionOk() (*string, bool) {
	if o == nil || o.ViewRecursion == nil {
		return nil, false
	}
	return o.ViewRecursion, true
}

// HasViewRecursion returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasViewRecursion() bool {
	if o != nil && o.ViewRecursion != nil {
		return true
	}

	return false
}

// SetViewRecursion gets a reference to the given string and assigns it to the ViewRecursion field.
func (o *DnsViewAddInput) SetViewRecursion(v string) {
	o.ViewRecursion = &v
}

// GetClassParametersToDelete returns the ClassParametersToDelete field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetClassParametersToDelete() []string {
	if o == nil || o.ClassParametersToDelete == nil {
		var ret []string
		return ret
	}
	return *o.ClassParametersToDelete
}

// GetClassParametersToDeleteOk returns a tuple with the ClassParametersToDelete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetClassParametersToDeleteOk() (*[]string, bool) {
	if o == nil || o.ClassParametersToDelete == nil {
		return nil, false
	}
	return o.ClassParametersToDelete, true
}

// HasClassParametersToDelete returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasClassParametersToDelete() bool {
	if o != nil && o.ClassParametersToDelete != nil {
		return true
	}

	return false
}

// SetClassParametersToDelete gets a reference to the given []string and assigns it to the ClassParametersToDelete field.
func (o *DnsViewAddInput) SetClassParametersToDelete(v []string) {
	o.ClassParametersToDelete = &v
}

// GetViewClassName returns the ViewClassName field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetViewClassName() string {
	if o == nil || o.ViewClassName == nil {
		var ret string
		return ret
	}
	return *o.ViewClassName
}

// GetViewClassNameOk returns a tuple with the ViewClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetViewClassNameOk() (*string, bool) {
	if o == nil || o.ViewClassName == nil {
		return nil, false
	}
	return o.ViewClassName, true
}

// HasViewClassName returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasViewClassName() bool {
	if o != nil && o.ViewClassName != nil {
		return true
	}

	return false
}

// SetViewClassName gets a reference to the given string and assigns it to the ViewClassName field.
func (o *DnsViewAddInput) SetViewClassName(v string) {
	o.ViewClassName = &v
}

// GetViewClassParameters returns the ViewClassParameters field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetViewClassParameters() []ApiClassParameterInputEntry {
	if o == nil || o.ViewClassParameters == nil {
		var ret []ApiClassParameterInputEntry
		return ret
	}
	return *o.ViewClassParameters
}

// GetViewClassParametersOk returns a tuple with the ViewClassParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetViewClassParametersOk() (*[]ApiClassParameterInputEntry, bool) {
	if o == nil || o.ViewClassParameters == nil {
		return nil, false
	}
	return o.ViewClassParameters, true
}

// HasViewClassParameters returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasViewClassParameters() bool {
	if o != nil && o.ViewClassParameters != nil {
		return true
	}

	return false
}

// SetViewClassParameters gets a reference to the given []ApiClassParameterInputEntry and assigns it to the ViewClassParameters field.
func (o *DnsViewAddInput) SetViewClassParameters(v []ApiClassParameterInputEntry) {
	o.ViewClassParameters = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *DnsViewAddInput) GetWarnings() string {
	if o == nil || o.Warnings == nil {
		var ret string
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsViewAddInput) GetWarningsOk() (*string, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *DnsViewAddInput) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given string and assigns it to the Warnings field.
func (o *DnsViewAddInput) SetWarnings(v string) {
	o.Warnings = &v
}

func (o DnsViewAddInput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ServerId != nil {
		toSerialize["server_id"] = o.ServerId
	}
	if o.ServerName != nil {
		toSerialize["server_name"] = o.ServerName
	}
	if o.ViewName != nil {
		toSerialize["view_name"] = o.ViewName
	}
	if o.ServerHostaddr != nil {
		toSerialize["server_hostaddr"] = o.ServerHostaddr
	}
	if o.ViewAllowQuery != nil {
		toSerialize["view_allow_query"] = o.ViewAllowQuery
	}
	if o.ViewAllowRecursion != nil {
		toSerialize["view_allow_recursion"] = o.ViewAllowRecursion
	}
	if o.ViewAllowTransfer != nil {
		toSerialize["view_allow_transfer"] = o.ViewAllowTransfer
	}
	if o.ViewMatchClients != nil {
		toSerialize["view_match_clients"] = o.ViewMatchClients
	}
	if o.ViewMatchTo != nil {
		toSerialize["view_match_to"] = o.ViewMatchTo
	}
	if o.ViewOrder != nil {
		toSerialize["view_order"] = o.ViewOrder
	}
	if o.ViewRecursion != nil {
		toSerialize["view_recursion"] = o.ViewRecursion
	}
	if o.ClassParametersToDelete != nil {
		toSerialize["class_parameters_to_delete"] = o.ClassParametersToDelete
	}
	if o.ViewClassName != nil {
		toSerialize["view_class_name"] = o.ViewClassName
	}
	if o.ViewClassParameters != nil {
		toSerialize["view_class_parameters"] = o.ViewClassParameters
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableDnsViewAddInput struct {
	value *DnsViewAddInput
	isSet bool
}

func (v NullableDnsViewAddInput) Get() *DnsViewAddInput {
	return v.value
}

func (v *NullableDnsViewAddInput) Set(val *DnsViewAddInput) {
	v.value = val
	v.isSet = true
}

func (v NullableDnsViewAddInput) IsSet() bool {
	return v.isSet
}

func (v *NullableDnsViewAddInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnsViewAddInput(val *DnsViewAddInput) *NullableDnsViewAddInput {
	return &NullableDnsViewAddInput{value: val, isSet: true}
}

func (v NullableDnsViewAddInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnsViewAddInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


