/*
SOLIDserver API

OpenAPI 3.0.2 API definition for SOLIDserver service from EfficientIP.<p>Copyright © 2000-2024 EfficientIP</p><p><em>All specifications and information regarding the products in this document are subject to change without notice and should not be construed as a commitment by EfficientIP. EfficientIP assumes no responsibility or liability for any mistakes or inaccuracies that may appear in this document. All statements and recommendations in this document are believed to be accurate but are presented without warranty. Users must take full responsibility for their application of any product.</em></p><p><em>This document aims at detailing EfficientIP proprietary solutions. As our solutions rely on several third-party products, created by other companies or organizations, it may redirect readers to third-party websites and documentation for further information. In such a case, EfficientIP cannot be liable or expected to provide said information on products they do maintain or created.</em></p><p>Generated (Friday 4th of October 2024 03:41:11 PM)</p>

API version: 2.0
Contact: support-api@efficientip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdsclient

import (
	"encoding/json"
)

// checks if the AppNodeEditInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppNodeEditInput{}

// AppNodeEditInput struct for AppNodeEditInput
type AppNodeEditInput struct {
	// The Fully Qualified Domain Name (FQDN) of the application the object belongs to.
	ApplicationFqdn *string `json:"application_fqdn,omitempty"`
	// The database identifier (ID) of the application the object belongs to.
	ApplicationId *int32 `json:"application_id,omitempty"`
	// The name of the application the object belongs to.
	ApplicationName *string `json:"application_name,omitempty"`
	// The database identifier (ID) of the node, a unique numeric key value automatically incremented when you add a node. Use the ID to specify the node of your choice.
	NodeId *int32 `json:"node_id,omitempty"`
	// The database identifier (ID) of the pool, a unique numeric key value automatically incremented when you add a pool. Use the ID to specify the pool of your choice.
	PoolId *int32 `json:"pool_id,omitempty"`
	// The name of the pool.
	PoolName *string `json:"pool_name,omitempty"`
	// The IPv4 or IPv6 address of the node.
	NodeHostaddr *string `json:"node_hostaddr,omitempty"`
	// The name of the node.
	NodeName *string `json:"node_name,omitempty"`
	// The administrative status of the node, managed (1) or unmanaged (0).
	AdminStatus *int32 `json:"admin_status,omitempty"`
	// The database identifier (ID) of the GSLB server associated with the application, a unique numeric key value automatically incremented when you add the server. Use it to identify the GSLB server of your choice.
	GslbserverId *int32 `json:"gslbserver_id,omitempty"`
	// The type of health check of the node.
	HealthcheckName *string `json:"healthcheck_name,omitempty"`
	// Internal use. Not documented.
	NodeStatus *string `json:"node_status,omitempty"`
	// The weight of the node, it sets which node is used first within the pool. It must be an integer between 0 and 255, where 0 sets a node as backup.
	NodeWeight *string `json:"node_weight,omitempty"`
	// A way to bypass <b>(accept) </b>any enabled rule that would return warning messages. If the service returns an error message, you cannot bypass the enabled rules.
	Warnings *string `json:"warnings,omitempty"`
}

// NewAppNodeEditInput instantiates a new AppNodeEditInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppNodeEditInput() *AppNodeEditInput {
	this := AppNodeEditInput{}
	return &this
}

// NewAppNodeEditInputWithDefaults instantiates a new AppNodeEditInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppNodeEditInputWithDefaults() *AppNodeEditInput {
	this := AppNodeEditInput{}
	return &this
}

// GetApplicationFqdn returns the ApplicationFqdn field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetApplicationFqdn() string {
	if o == nil || IsNil(o.ApplicationFqdn) {
		var ret string
		return ret
	}
	return *o.ApplicationFqdn
}

// GetApplicationFqdnOk returns a tuple with the ApplicationFqdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetApplicationFqdnOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicationFqdn) {
		return nil, false
	}
	return o.ApplicationFqdn, true
}

// HasApplicationFqdn returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasApplicationFqdn() bool {
	if o != nil && !IsNil(o.ApplicationFqdn) {
		return true
	}

	return false
}

// SetApplicationFqdn gets a reference to the given string and assigns it to the ApplicationFqdn field.
func (o *AppNodeEditInput) SetApplicationFqdn(v string) {
	o.ApplicationFqdn = &v
}

// GetApplicationId returns the ApplicationId field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetApplicationId() int32 {
	if o == nil || IsNil(o.ApplicationId) {
		var ret int32
		return ret
	}
	return *o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetApplicationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ApplicationId) {
		return nil, false
	}
	return o.ApplicationId, true
}

// HasApplicationId returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasApplicationId() bool {
	if o != nil && !IsNil(o.ApplicationId) {
		return true
	}

	return false
}

// SetApplicationId gets a reference to the given int32 and assigns it to the ApplicationId field.
func (o *AppNodeEditInput) SetApplicationId(v int32) {
	o.ApplicationId = &v
}

// GetApplicationName returns the ApplicationName field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetApplicationName() string {
	if o == nil || IsNil(o.ApplicationName) {
		var ret string
		return ret
	}
	return *o.ApplicationName
}

// GetApplicationNameOk returns a tuple with the ApplicationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetApplicationNameOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicationName) {
		return nil, false
	}
	return o.ApplicationName, true
}

// HasApplicationName returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasApplicationName() bool {
	if o != nil && !IsNil(o.ApplicationName) {
		return true
	}

	return false
}

// SetApplicationName gets a reference to the given string and assigns it to the ApplicationName field.
func (o *AppNodeEditInput) SetApplicationName(v string) {
	o.ApplicationName = &v
}

// GetNodeId returns the NodeId field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetNodeId() int32 {
	if o == nil || IsNil(o.NodeId) {
		var ret int32
		return ret
	}
	return *o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetNodeIdOk() (*int32, bool) {
	if o == nil || IsNil(o.NodeId) {
		return nil, false
	}
	return o.NodeId, true
}

// HasNodeId returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasNodeId() bool {
	if o != nil && !IsNil(o.NodeId) {
		return true
	}

	return false
}

// SetNodeId gets a reference to the given int32 and assigns it to the NodeId field.
func (o *AppNodeEditInput) SetNodeId(v int32) {
	o.NodeId = &v
}

// GetPoolId returns the PoolId field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetPoolId() int32 {
	if o == nil || IsNil(o.PoolId) {
		var ret int32
		return ret
	}
	return *o.PoolId
}

// GetPoolIdOk returns a tuple with the PoolId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetPoolIdOk() (*int32, bool) {
	if o == nil || IsNil(o.PoolId) {
		return nil, false
	}
	return o.PoolId, true
}

// HasPoolId returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasPoolId() bool {
	if o != nil && !IsNil(o.PoolId) {
		return true
	}

	return false
}

// SetPoolId gets a reference to the given int32 and assigns it to the PoolId field.
func (o *AppNodeEditInput) SetPoolId(v int32) {
	o.PoolId = &v
}

// GetPoolName returns the PoolName field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetPoolName() string {
	if o == nil || IsNil(o.PoolName) {
		var ret string
		return ret
	}
	return *o.PoolName
}

// GetPoolNameOk returns a tuple with the PoolName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetPoolNameOk() (*string, bool) {
	if o == nil || IsNil(o.PoolName) {
		return nil, false
	}
	return o.PoolName, true
}

// HasPoolName returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasPoolName() bool {
	if o != nil && !IsNil(o.PoolName) {
		return true
	}

	return false
}

// SetPoolName gets a reference to the given string and assigns it to the PoolName field.
func (o *AppNodeEditInput) SetPoolName(v string) {
	o.PoolName = &v
}

// GetNodeHostaddr returns the NodeHostaddr field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetNodeHostaddr() string {
	if o == nil || IsNil(o.NodeHostaddr) {
		var ret string
		return ret
	}
	return *o.NodeHostaddr
}

// GetNodeHostaddrOk returns a tuple with the NodeHostaddr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetNodeHostaddrOk() (*string, bool) {
	if o == nil || IsNil(o.NodeHostaddr) {
		return nil, false
	}
	return o.NodeHostaddr, true
}

// HasNodeHostaddr returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasNodeHostaddr() bool {
	if o != nil && !IsNil(o.NodeHostaddr) {
		return true
	}

	return false
}

// SetNodeHostaddr gets a reference to the given string and assigns it to the NodeHostaddr field.
func (o *AppNodeEditInput) SetNodeHostaddr(v string) {
	o.NodeHostaddr = &v
}

// GetNodeName returns the NodeName field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetNodeName() string {
	if o == nil || IsNil(o.NodeName) {
		var ret string
		return ret
	}
	return *o.NodeName
}

// GetNodeNameOk returns a tuple with the NodeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetNodeNameOk() (*string, bool) {
	if o == nil || IsNil(o.NodeName) {
		return nil, false
	}
	return o.NodeName, true
}

// HasNodeName returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasNodeName() bool {
	if o != nil && !IsNil(o.NodeName) {
		return true
	}

	return false
}

// SetNodeName gets a reference to the given string and assigns it to the NodeName field.
func (o *AppNodeEditInput) SetNodeName(v string) {
	o.NodeName = &v
}

// GetAdminStatus returns the AdminStatus field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetAdminStatus() int32 {
	if o == nil || IsNil(o.AdminStatus) {
		var ret int32
		return ret
	}
	return *o.AdminStatus
}

// GetAdminStatusOk returns a tuple with the AdminStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetAdminStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.AdminStatus) {
		return nil, false
	}
	return o.AdminStatus, true
}

// HasAdminStatus returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasAdminStatus() bool {
	if o != nil && !IsNil(o.AdminStatus) {
		return true
	}

	return false
}

// SetAdminStatus gets a reference to the given int32 and assigns it to the AdminStatus field.
func (o *AppNodeEditInput) SetAdminStatus(v int32) {
	o.AdminStatus = &v
}

// GetGslbserverId returns the GslbserverId field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetGslbserverId() int32 {
	if o == nil || IsNil(o.GslbserverId) {
		var ret int32
		return ret
	}
	return *o.GslbserverId
}

// GetGslbserverIdOk returns a tuple with the GslbserverId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetGslbserverIdOk() (*int32, bool) {
	if o == nil || IsNil(o.GslbserverId) {
		return nil, false
	}
	return o.GslbserverId, true
}

// HasGslbserverId returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasGslbserverId() bool {
	if o != nil && !IsNil(o.GslbserverId) {
		return true
	}

	return false
}

// SetGslbserverId gets a reference to the given int32 and assigns it to the GslbserverId field.
func (o *AppNodeEditInput) SetGslbserverId(v int32) {
	o.GslbserverId = &v
}

// GetHealthcheckName returns the HealthcheckName field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetHealthcheckName() string {
	if o == nil || IsNil(o.HealthcheckName) {
		var ret string
		return ret
	}
	return *o.HealthcheckName
}

// GetHealthcheckNameOk returns a tuple with the HealthcheckName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetHealthcheckNameOk() (*string, bool) {
	if o == nil || IsNil(o.HealthcheckName) {
		return nil, false
	}
	return o.HealthcheckName, true
}

// HasHealthcheckName returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasHealthcheckName() bool {
	if o != nil && !IsNil(o.HealthcheckName) {
		return true
	}

	return false
}

// SetHealthcheckName gets a reference to the given string and assigns it to the HealthcheckName field.
func (o *AppNodeEditInput) SetHealthcheckName(v string) {
	o.HealthcheckName = &v
}

// GetNodeStatus returns the NodeStatus field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetNodeStatus() string {
	if o == nil || IsNil(o.NodeStatus) {
		var ret string
		return ret
	}
	return *o.NodeStatus
}

// GetNodeStatusOk returns a tuple with the NodeStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetNodeStatusOk() (*string, bool) {
	if o == nil || IsNil(o.NodeStatus) {
		return nil, false
	}
	return o.NodeStatus, true
}

// HasNodeStatus returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasNodeStatus() bool {
	if o != nil && !IsNil(o.NodeStatus) {
		return true
	}

	return false
}

// SetNodeStatus gets a reference to the given string and assigns it to the NodeStatus field.
func (o *AppNodeEditInput) SetNodeStatus(v string) {
	o.NodeStatus = &v
}

// GetNodeWeight returns the NodeWeight field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetNodeWeight() string {
	if o == nil || IsNil(o.NodeWeight) {
		var ret string
		return ret
	}
	return *o.NodeWeight
}

// GetNodeWeightOk returns a tuple with the NodeWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetNodeWeightOk() (*string, bool) {
	if o == nil || IsNil(o.NodeWeight) {
		return nil, false
	}
	return o.NodeWeight, true
}

// HasNodeWeight returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasNodeWeight() bool {
	if o != nil && !IsNil(o.NodeWeight) {
		return true
	}

	return false
}

// SetNodeWeight gets a reference to the given string and assigns it to the NodeWeight field.
func (o *AppNodeEditInput) SetNodeWeight(v string) {
	o.NodeWeight = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *AppNodeEditInput) GetWarnings() string {
	if o == nil || IsNil(o.Warnings) {
		var ret string
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppNodeEditInput) GetWarningsOk() (*string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *AppNodeEditInput) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given string and assigns it to the Warnings field.
func (o *AppNodeEditInput) SetWarnings(v string) {
	o.Warnings = &v
}

func (o AppNodeEditInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppNodeEditInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApplicationFqdn) {
		toSerialize["application_fqdn"] = o.ApplicationFqdn
	}
	if !IsNil(o.ApplicationId) {
		toSerialize["application_id"] = o.ApplicationId
	}
	if !IsNil(o.ApplicationName) {
		toSerialize["application_name"] = o.ApplicationName
	}
	if !IsNil(o.NodeId) {
		toSerialize["node_id"] = o.NodeId
	}
	if !IsNil(o.PoolId) {
		toSerialize["pool_id"] = o.PoolId
	}
	if !IsNil(o.PoolName) {
		toSerialize["pool_name"] = o.PoolName
	}
	if !IsNil(o.NodeHostaddr) {
		toSerialize["node_hostaddr"] = o.NodeHostaddr
	}
	if !IsNil(o.NodeName) {
		toSerialize["node_name"] = o.NodeName
	}
	if !IsNil(o.AdminStatus) {
		toSerialize["admin_status"] = o.AdminStatus
	}
	if !IsNil(o.GslbserverId) {
		toSerialize["gslbserver_id"] = o.GslbserverId
	}
	if !IsNil(o.HealthcheckName) {
		toSerialize["healthcheck_name"] = o.HealthcheckName
	}
	if !IsNil(o.NodeStatus) {
		toSerialize["node_status"] = o.NodeStatus
	}
	if !IsNil(o.NodeWeight) {
		toSerialize["node_weight"] = o.NodeWeight
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

type NullableAppNodeEditInput struct {
	value *AppNodeEditInput
	isSet bool
}

func (v NullableAppNodeEditInput) Get() *AppNodeEditInput {
	return v.value
}

func (v *NullableAppNodeEditInput) Set(val *AppNodeEditInput) {
	v.value = val
	v.isSet = true
}

func (v NullableAppNodeEditInput) IsSet() bool {
	return v.isSet
}

func (v *NullableAppNodeEditInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppNodeEditInput(val *AppNodeEditInput) *NullableAppNodeEditInput {
	return &NullableAppNodeEditInput{value: val, isSet: true}
}

func (v NullableAppNodeEditInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppNodeEditInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
